version: '3.9'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --certificatesResolvers.le.acme.email=you@your-email.com
      - --certificatesResolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesResolvers.le.acme.httpChallenge.entryPoint=web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt:/letsencrypt
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: water_level_bot
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d water_level_bot"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  app:
    build: .
    container_name: waterguardbot_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DOMAIN_URL: https://waterlevelleti.ru
      TELEGRAM_BOT_NAME: WaterGuardBot
      TELEGRAM_BOT_TOKEN: 7753531757:AAF8CI7_GVs-i4SIHYqun9tyP5U998E-H3c
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/water_level_bot
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      YANDEX_API_KEY: 07f75823-cbb0-4046-83ee-d4dc403b9329
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.waterguardbot.rule=Host(`waterlevelleti.ru`)"
      - "traefik.http.routers.waterguardbot.entrypoints=websecure"
      - "traefik.http.routers.waterguardbot.tls.certresolver=le"
      - "traefik.http.services.waterguardbot.loadbalancer.server.port=80"
    networks:
      - web
    restart: unless-stopped

volumes:
  pgdata:
    driver: local
  traefik_letsencrypt:

networks:
  web:
    external: false