server:
  port: 80
  address: 0.0.0.0

telegram:
  webhook-path: https://b979-2a01-e5c0-4614-00-2.ngrok-free.app/webhook
  bot-name: WaterGuardBot
  bot-token: 7753531757:AAF8CI7_GVs-i4SIHYqun9tyP5U998E-H3c

spring:
  application:
    name: waterlevelbot
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://213.176.67.231:5430/water_level_bot
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

yandex:
  api:
    key: 07f75823-cbb0-4046-83ee-d4dc403b9329



domain:
  url: https://b979-2a01-e5c0-4614-00-2.ngrok-free.app/statistics